from __future__ import unicode_literals

from modelos.Tipo_terapia_model import Tipo_terapia
from modelos.Terapista_model import Terapista
from modelos.Terapia__Tipo_terapia_models import Terapia__Tipo_terapia

